### PR TITLE
 Add support to get pipeline instances

### PR DESCRIPTION
**Pull request by aerostitch**
Hi!

Let me know if there are stuffs you want me to change.
There are some structs that I put in separate files in prevision of other stuffs that will come later.

Thanks!
Joseph

Note: I'll have several other PR coming up in the next day or 2 depending on the time I have.
Note 2: the `Accept` header is not set here because if you set it in the version we have inhouse (17.12.0).

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
The changes LGTM @aerostitch 

Let me know if I can merge these or if you're planning to add more changes as part of this PR.

**Comment by aerostitch** [comment]
You can merge these @ashwanthkumar . Not sure exactly when I'll be able to make the other things I want to add.
Thanks a lot! :)

**Comment by ashwanthkumar** [comment]
Thanks for the changes 🎉

**Comment by aerostitch** [comment]
Thanks for the review & merge! :)

**Pull request merged**
